site_name: ATC command semantic parsing
site_url: https://sash-tim.github.io/ATC-parsing/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Content:
      - Getting Started: getting_started.md
      - GPT-5 and ATC command understanding: gpt_atc_understanding.md

markdown_extensions:
  - tables
  - pymdownx.extra
  - pymdownx.superfences

